import json
from datetime import date, timedelta

from ai.graph.state import TravelState
from integrations.openai import generate_json


ACTIVITY_SCHEMA = {
    "type": "object",
    "properties": {
        "activity": {
            "type": "string"
        },
        "location": {
            "type": "string"
        },
        "est_cost": {
            "type": "integer"
        },
    },
    "required": [
        "activity",
        "location",
        "est_cost",
    ],
}


DAY_SCHEMA = {
    "type": "object",
    "properties": {
        "date": {
            "type": "string"
        },
        "day_number": {
            "type": "integer"
        },
        "morning": {
            "type": "array",
            "items": ACTIVITY_SCHEMA,
        },
        "afternoon": {
            "type": "array",
            "items": ACTIVITY_SCHEMA,
        },
        "evening": {
            "type": "array",
            "items": ACTIVITY_SCHEMA,
        },
    },
    "required": [
        "date",
        "day_number",
        "morning",
        "afternoon",
        "evening",
    ],
}


ITINERARY_SCHEMA = {
    "type": "object",
    "properties": {
        "days": {
            "type": "array",
            "items": DAY_SCHEMA,
        }
    },
    "required": [
        "days"
    ],
}


SYSTEM_PROMPT = """
You are TravelAI's itinerary generation agent.

Generate a realistic day-by-day travel itinerary using the
provided travel data and the smart budget allocation.

The user provides:

- destination
- origin
- travel dates
- number of travelers
- total budget
- preferences
- flight results
- hotel results
- weather information
- retrieved user memories
- smart budget allocation

IMPORTANT:

The smart budget allocation is a planning constraint.
Use it when deciding how expensive the activities and food
should be.

Rules:

1. Generate exactly one itinerary day for every requested travel date.

2. Use the exact requested dates.

3. Use the exact day numbers.

4. Generate activities appropriate for the destination.

5. Respect the user's preferences.

6. Each day must contain:
   - morning
   - afternoon
   - evening

7. Each activity must contain:
   - activity
   - location
   - est_cost

8. est_cost must be an integer in INR.

9. Keep activity costs within the allocated activities budget
   as much as reasonably possible.

10. Prefer free or low-cost activities when the activity budget
    is limited.

11. If the user's preferences involve nightlife, adventure,
    sightseeing, water sports, food, or other paid activities,
    use the available activity budget intelligently.

12. Do not create fake flights.

13. Do not create fake hotels.

14. Do not invent weather information.

15. Use the provided flight and hotel results as real provider data.

16. Do not invent flight prices or hotel prices.

17. Do not treat the flight price as an additional per-person
    cost if the provided flight result already represents the
    queried traveler count.

18. Do not exceed the overall user budget intentionally.

19. Keep the itinerary realistic. Do not schedule too many
    activities in one time slot.

20. Use retrieved user memories only when relevant.

21. Do not add explanations.

22. Return only the requested structured JSON.
"""


def itinerary_node(state: TravelState) -> dict:

    constraints = state["constraints"]

    start_date = date.fromisoformat(
        constraints["start_date"]
    )

    end_date = date.fromisoformat(
        constraints["end_date"]
    )

    total_days = (
        end_date - start_date
    ).days + 1

    requested_dates = []

    for index in range(total_days):

        current_date = (
            start_date + timedelta(days=index)
        ).isoformat()

        requested_dates.append(
            {
                "date": current_date,
                "day_number": index + 1,
            }
        )

    # Smart budget allocation generated by
    # optimization/budget_allocator.py
    budget_allocation = state.get(
        "budget_allocation",
        {}
    )

    planner_input = {
        "destination": constraints["destination"],

        "origin": constraints.get(
            "origin"
        ),

        "destination_code": constraints.get(
            "destination_code"
        ),

        "start_date": constraints["start_date"],

        "end_date": constraints["end_date"],

        "travelers": constraints["travelers"],

        "budget": constraints["budget"],

        "preferences": constraints.get(
            "preferences",
            []
        ),

        "requested_days": requested_dates,

        "flights": state.get(
            "flights",
            []
        ),

        "hotels": state.get(
            "hotels",
            []
        ),

        "weather": state.get(
            "weather",
            []
        ),

        "user_memory": state.get(
            "user_memory",
            []
        ),

        # NEW:
        # Smart budget allocation information
        "budget_allocation": budget_allocation,
    }

    print(
        "\n--- SMART BUDGET ALLOCATION ---"
    )

    print(
        json.dumps(
            budget_allocation,
            indent=2,
            ensure_ascii=False,
            default=str,
        )
    )

    result = generate_json(
        system_prompt=SYSTEM_PROMPT,

        user_message=json.dumps(
            planner_input,
            ensure_ascii=False,
            default=str,
        ),

        response_schema=ITINERARY_SCHEMA,
    )

    if not result:

        raise RuntimeError(
            "Itinerary Agent returned empty response"
        )

    print(
        "\n--- GEMINI ITINERARY RESPONSE ---"
    )

    print(result)

    try:

        generated = json.loads(
            result
        )

    except json.JSONDecodeError as exc:

        raise RuntimeError(
            "Gemini returned invalid itinerary JSON"
        ) from exc

    generated_days = generated.get(
        "days",
        []
    )

    if len(generated_days) != total_days:

        raise RuntimeError(
            f"Itinerary Agent returned "
            f"{len(generated_days)} days; "
            f"expected {total_days}"
        )

    final_days = []

    weather_data = state.get(
        "weather",
        []
    )

    for index, day in enumerate(
        generated_days
    ):

        expected_date = (
            start_date
            + timedelta(days=index)
        ).isoformat()

        expected_day_number = index + 1

        # Force deterministic date/day values.
        day["date"] = expected_date

        day["day_number"] = (
            expected_day_number
        )

        # --------------------------------------------------------
        # ATTACH WEATHER TO THE CORRECT DAY
        # --------------------------------------------------------
        #
        # integrations/weather.py returns:
        #
        # {
        #     "date": "2026-09-29",
        #     "temp_c": 27.0,
        #     "condition": "few clouds"
        # }
        #
        # Older weather formats may use "datetime", so support
        # both formats.
        # --------------------------------------------------------

        day_weather = {
            "condition": "unavailable",
            "temp_c": None,
        }

        for weather_item in weather_data:

            weather_date = weather_item.get("date")

            # Backward compatibility with datetime-based weather
            if not weather_date:
                weather_datetime = weather_item.get(
                    "datetime"
                )

                if weather_datetime:
                    weather_date = str(
                        weather_datetime
                    )[:10]

            if not weather_date:
                continue

            weather_date = str(weather_date)[:10]

            if weather_date == expected_date:

                day_weather = {
                    "condition": weather_item.get(
                        "condition"
                    ) or "unavailable",

                    "temp_c": weather_item.get(
                        "temp_c"
                    ),
                }

                break
        final_days.append(
            {
                "date": expected_date,

                "day_number": expected_day_number,

                "is_editable": True,

                "weather": day_weather,

                "slots": {
                    "morning": day.get(
                        "morning",
                        []
                    ),

                    "afternoon": day.get(
                        "afternoon",
                        []
                    ),

                    "evening": day.get(
                        "evening",
                        []
                    ),
                },
            }
        )

    itinerary = {
        "days": final_days
    }

    return {
        "itinerary": itinerary,

        "status": "itinerary_generated",
    }
# ============================================================
# PARTIAL REPLANNING
# ============================================================

REPLAN_SYSTEM_PROMPT = """
You are TravelAI's itinerary replanning agent.

The user already has an existing travel itinerary.

Your job is to regenerate ONLY the requested affected days.

IMPORTANT RULES:

1. Generate ONLY the requested day numbers.

2. Do NOT generate any other days.

3. Preserve the original travel dates.

4. Preserve the original day numbers.

5. Use the user's replanning message as the primary instruction.

6. Respect the original destination, budget and preferences.

7. Use available weather information when relevant.

8. Use retrieved user memories when relevant.

9. Keep the new activities realistic.

10. Each requested day must contain:
    - morning
    - afternoon
    - evening

11. Each activity must contain:
    - activity
    - location
    - est_cost

12. est_cost must be an integer in INR.

13. Do not invent flights or hotels.

14. Do not invent weather information.

15. Do not modify days that were not requested.

16. Do not add explanations.

17. Return only structured JSON.
"""


REPLAN_DAY_SCHEMA = {
    "type": "object",
    "properties": {
        "date": {
            "type": "string"
        },
        "day_number": {
            "type": "integer"
        },
        "morning": {
            "type": "array",
            "items": ACTIVITY_SCHEMA,
        },
        "afternoon": {
            "type": "array",
            "items": ACTIVITY_SCHEMA,
        },
        "evening": {
            "type": "array",
            "items": ACTIVITY_SCHEMA,
        },
    },
    "required": [
        "date",
        "day_number",
        "morning",
        "afternoon",
        "evening",
    ],
}


REPLAN_SCHEMA = {
    "type": "object",
    "properties": {
        "days": {
            "type": "array",
            "items": REPLAN_DAY_SCHEMA,
        }
    },
    "required": [
        "days"
    ],
}


def replan_itinerary(
    state: TravelState,
    affected_days: list[int],
    message: str,
) -> dict:
    """
    Regenerate only the requested itinerary days.

    Existing non-affected days are preserved by the caller.
    """

    itinerary = state.get(
        "itinerary",
        {}
    )

    existing_days = itinerary.get(
        "days",
        []
    )

    if not existing_days:
        raise RuntimeError(
            "Cannot replan because the existing itinerary is missing."
        )

    affected_days = sorted(
        set(affected_days)
    )

    existing_day_map = {
        day.get("day_number"): day
        for day in existing_days
    }

    # --------------------------------------------------------
    # Validate requested days
    # --------------------------------------------------------

    missing_days = [
        day_number
        for day_number in affected_days
        if day_number not in existing_day_map
    ]

    if missing_days:
        raise ValueError(
            f"Invalid affected days: {missing_days}"
        )

    # --------------------------------------------------------
    # Build only the requested days
    # --------------------------------------------------------

    days_to_replan = []

    for day_number in affected_days:

        existing_day = existing_day_map[
            day_number
        ]

        days_to_replan.append(
            {
                "date": existing_day.get(
                    "date"
                ),
                "day_number": day_number,
                "current_day": existing_day,
            }
        )

    planner_input = {
        "replanning_message": message,

        "affected_days": affected_days,

        "destination": state.get(
            "constraints",
            {}
        ).get(
            "destination"
        ),

        "origin": state.get(
            "constraints",
            {}
        ).get(
            "origin"
        ),

        "start_date": state.get(
            "constraints",
            {}
        ).get(
            "start_date"
        ),

        "end_date": state.get(
            "constraints",
            {}
        ).get(
            "end_date"
        ),

        "travelers": state.get(
            "constraints",
            {}
        ).get(
            "travelers"
        ),

        "budget": state.get(
            "constraints",
            {}
        ).get(
            "budget"
        ),

        "preferences": state.get(
            "constraints",
            {}
        ).get(
            "preferences",
            []
        ),

        "budget_allocation": state.get(
            "budget_allocation",
            {}
        ),

        "flights": state.get(
            "flights",
            []
        ),

        "hotels": state.get(
            "hotels",
            []
        ),

        "weather": state.get(
            "weather",
            []
        ),

        "user_memory": state.get(
            "user_memory",
            []
        ),

        "days_to_replan": days_to_replan,
    }

    print(
        "\n--- PARTIAL REPLANNING ---"
    )

    print(
        f"Affected days: {affected_days}"
    )

    print(
        f"Message: {message}"
    )

    result = generate_json(
        system_prompt=REPLAN_SYSTEM_PROMPT,

        user_message=json.dumps(
            planner_input,
            ensure_ascii=False,
            default=str,
        ),

        response_schema=REPLAN_SCHEMA,
    )

    if not result:

        raise RuntimeError(
            "Replan Agent returned empty response"
        )

    print(
        "\n--- GEMINI REPLAN RESPONSE ---"
    )

    print(result)

    try:

        generated = json.loads(
            result
        )

    except json.JSONDecodeError as exc:

        raise RuntimeError(
            "Gemini returned invalid replan JSON"
        ) from exc

    replanned_days = generated.get(
        "days",
        []
    )

    if len(replanned_days) != len(
        affected_days
    ):

        raise RuntimeError(
            f"Replan Agent returned "
            f"{len(replanned_days)} days; "
            f"expected {len(affected_days)}"
        )

    replanned_map = {}

    for day in replanned_days:

        day_number = day.get(
            "day_number"
        )

        if day_number not in affected_days:

            raise RuntimeError(
                f"Replan Agent modified "
                f"unexpected day {day_number}"
            )

        original_day = existing_day_map[
            day_number
        ]

        # ----------------------------------------------------
        # Force original date/day number
        # ----------------------------------------------------

        day["date"] = original_day.get(
            "date"
        )

        day["day_number"] = day_number

        # ----------------------------------------------------
        # Preserve backend-controlled fields
        # ----------------------------------------------------

        day_weather = original_day.get(
            "weather",
            {
                "condition": "unavailable",
                "temp_c": None,
            },
        )

        replanned_map[
            day_number
        ] = {
            "date": day["date"],

            "day_number": day_number,

            "is_editable": True,

            "weather": day_weather,

            "slots": {
                "morning": day.get(
                    "morning",
                    []
                ),

                "afternoon": day.get(
                    "afternoon",
                    []
                ),

                "evening": day.get(
                    "evening",
                    []
                ),
            },
        }

    # --------------------------------------------------------
    # Merge with existing itinerary
    # --------------------------------------------------------

    final_days = []

    for existing_day in existing_days:

        day_number = existing_day.get(
            "day_number"
        )

        if day_number in replanned_map:

            final_days.append(
                replanned_map[
                    day_number
                ]
            )

        else:

            # IMPORTANT:
            # Non-affected days are copied unchanged.
            final_days.append(
                existing_day
            )

    final_days.sort(
        key=lambda day: day.get(
            "day_number",
            0
        )
    )

    return {
        "days": final_days
    }